
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NavbarC from "./Components/Navbar/page";
import { AppProvider } from "./context";
import LoadingBarC from "./LoadingBarC";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MalahimBot",
  description: "Generated by Malahim",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <AppProvider>
        <LoadingBarC/>
       <NavbarC/>
        <Toaster position="top-center" />
        {children}
        </AppProvider>
        </body>
    </html>
  );
}
